config/routes.rb
Rails.application.routes.draw do
resources :users, only: [:create, :new, :show]
resource :session, only: [:create, :new, :destroy]
resources :bands do
  resources :albums, only: [:new]
end
resources :albums, except: [:index, :new] do
  resources :tracks, only: [:new]
end
resources :tracks, except: [:index, :new]

  root to: redirect("/session/new")

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  name       :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
    validates :name, :band_id, presence: true
  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id
  )
  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :album_id
  )
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id
  )
  has_many(
    :tracks,
    through: :albums,
    source: :tracks
  )
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  name       :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base
    validates :name, :album_id, presence: true
  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id
  )
  has_one(
    :band,
    through: :album,
    source: :band
  )
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, presence: true, uniqueness: true
  attr_reader :password
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user
      # byebug
      if user.is_password?(password)
        # return user if right credentials
        user
      end

    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album.band_id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @band_id = params[:band_id]
    @bands = Band.all
  end

  def album_params
    self.params.require(:album).permit(:name, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
   helper_method :current_user, :logged_in?
  def current_user
    @current_user = User.find_by(session_token: self.session[:session_token])
  end
  def logged_in?
    !current_user.nil?
  end
  def log_in_user!(user)
    user.reset_session_token!
     self.session[:session_token] = user.session_token
  end
  def log_out!
    current_user.reset_session_token!
    self.session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end
  def show
    @band = Band.find(params[:id])
  end
  def new

  end
  def create
    Band.create!(band_params)
    @bands = Band.all
    render :index
  end
  def band_params
    self.params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user
      log_in_user!(user)
      redirect_to bands_url
    else
      render text: "Login unsuccessful!"
    end
    # user.reset_session_token!
    # session[:session_token] = nil
  end
  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
    @track = Track.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end
  def create
    user = User.new(user_params)
    user.save!
    redirect_to user_url(user.id)
  end
  def show
    @current_user = current_user
    render :show
  end
  def user_params
    self.params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h1>Create an album!</h1>
<form action=<%= albums_url %> method="post">
  <label for="album">Enter album name<label>
  <input type="text" name=album[name] id="album">
  <select name="album[band_id]">
    <%@bands.each do |band|%>
      <option value=<%=band.id%> <%="selected" if band.id == @band_id.to_i %>> <%=band.name%></option>
    <%end%>
</select>
<input type="submit" value="Create album!">
</form>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<% @album.tracks.each do |track| %>
  <a href=<%= track_url(track.id) %>><%=track.name%></a>
  <br>
<% end %>

app/views/bands/index.html.erb
<h1>Bands</h1>
<% @bands.each do |band| %>
<a href=<%= band_url(band.id) %>><%= band.name %></a>
<br>
<%end%>
<hr>
<a href=<%= new_band_url %>>Make a new band!<a>

app/views/bands/new.html.erb
<h1>Create a band</h1>
<form action=<%= bands_url %> method="post">
  <label for="band">Enter band name<label>
  <input type="text" name=band[name] id="band">

<input type="submit" value="Create band!">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h2>Albums  </h2>
<br>
<% @band.albums.each do |album| %>
  <a href=<%= album_url(album.id) %>><%=album.name%></a>
  <br>
<% end %>
<hr>
<a href=<%= new_band_album_url(@band.id) %>>Make a new album!<a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
</head>
<body>
<%  if logged_in? %>
<%= current_user.email if logged_in? %>
<%= button_to "Logout", session_url, method: :delete %>
<hr>
<% end %>

<%= yield %>

</body>
</html>

app/views/tracks/show.html.erb
<h1><%= @track.band.name + " - " + @track.name %></h1>

app/views/users/show.html.erb
Logged in user: <%= @current_user.email %>
<br>